version: '3'

services:
    website:
        build:
            context: .
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./site/:/var/www/
        restart: always