version: '3'

services:
    website:
        build:
            context: .
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./site/:/var/www/
            - ./certbot/letsencrypt/:/etc/letsencrypt/
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always